[package]
name = "rust"
version = "0.1.0"
edition = "2018"
authors = ["Dennis Kobert"]

[lib]
name = "rust"
crate-type = ["staticlib"]

[dependencies]
#libc = {path="libc"}#, features=["rustc-dep-of-std"]}
